on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check PR title length
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Pull Request Title: $PR_TITLE"
          LENGTH=${#PR_TITLE}
          if [ $LENGTH -lt 10 ]; then
            echo "The Pull Request title is too short. It must be at least 10 characters long."
            exit 1
          fi
          echo "The Pull Request title is valid."


